// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_type.sql

package repository

import (
	"context"
)

const getGameTypes = `-- name: GetGameTypes :many
SELECT id, created_at, updated_at, label FROM game_type
`

func (q *Queries) GetGameTypes(ctx context.Context) ([]GameType, error) {
	rows, err := q.db.Query(ctx, getGameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameType
	for rows.Next() {
		var i GameType
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
