// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Game struct {
	Uuid          uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	GameTypeID    int32
	Player1Piece  string
	Player2Piece  string
	AiPlayerID    int16
	TerminalState int16
}

type GameType struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Label     string
}

type MoveEvent struct {
	Uuid          uuid.UUID
	GameUuid      uuid.UUID
	TraceUuid     *uuid.UUID
	MoveSequence  int16
	PlayerID      int16
	PostMoveState []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type TraceCache struct {
	Uuid                 uuid.UUID
	PrePostMoveStateHash []byte
	Trace                []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
