// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/trace.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// For the float64 activations from the neural network forward pass
type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer1        []float64              `protobuf:"fixed64,1,rep,packed,name=layer1,proto3" json:"layer1,omitempty"` // 18 activations
	Layer2        []float64              `protobuf:"fixed64,2,rep,packed,name=layer2,proto3" json:"layer2,omitempty"` // 32
	Layer3        []float64              `protobuf:"fixed64,3,rep,packed,name=layer3,proto3" json:"layer3,omitempty"` // 32
	Layer4        []float64              `protobuf:"fixed64,4,rep,packed,name=layer4,proto3" json:"layer4,omitempty"` // 32
	Layer5        []float64              `protobuf:"fixed64,5,rep,packed,name=layer5,proto3" json:"layer5,omitempty"` // 9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_proto_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_proto_trace_proto_rawDescGZIP(), []int{0}
}

func (x *Trace) GetLayer1() []float64 {
	if x != nil {
		return x.Layer1
	}
	return nil
}

func (x *Trace) GetLayer2() []float64 {
	if x != nil {
		return x.Layer2
	}
	return nil
}

func (x *Trace) GetLayer3() []float64 {
	if x != nil {
		return x.Layer3
	}
	return nil
}

func (x *Trace) GetLayer4() []float64 {
	if x != nil {
		return x.Layer4
	}
	return nil
}

func (x *Trace) GetLayer5() []float64 {
	if x != nil {
		return x.Layer5
	}
	return nil
}

var File_proto_trace_proto protoreflect.FileDescriptor

const file_proto_trace_proto_rawDesc = "" +
	"\n" +
	"\x11proto/trace.proto\x12\ttcubed.pb\"\x7f\n" +
	"\x05Trace\x12\x16\n" +
	"\x06layer1\x18\x01 \x03(\x01R\x06layer1\x12\x16\n" +
	"\x06layer2\x18\x02 \x03(\x01R\x06layer2\x12\x16\n" +
	"\x06layer3\x18\x03 \x03(\x01R\x06layer3\x12\x16\n" +
	"\x06layer4\x18\x04 \x03(\x01R\x06layer4\x12\x16\n" +
	"\x06layer5\x18\x05 \x03(\x01R\x06layer5B\x11Z\x0f/internal/pb;pbb\x06proto3"

var (
	file_proto_trace_proto_rawDescOnce sync.Once
	file_proto_trace_proto_rawDescData []byte
)

func file_proto_trace_proto_rawDescGZIP() []byte {
	file_proto_trace_proto_rawDescOnce.Do(func() {
		file_proto_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trace_proto_rawDesc), len(file_proto_trace_proto_rawDesc)))
	})
	return file_proto_trace_proto_rawDescData
}

var file_proto_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_trace_proto_goTypes = []any{
	(*Trace)(nil), // 0: tcubed.pb.Trace
}
var file_proto_trace_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_trace_proto_init() }
func file_proto_trace_proto_init() {
	if File_proto_trace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trace_proto_rawDesc), len(file_proto_trace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_trace_proto_goTypes,
		DependencyIndexes: file_proto_trace_proto_depIdxs,
		MessageInfos:      file_proto_trace_proto_msgTypes,
	}.Build()
	File_proto_trace_proto = out.File
	file_proto_trace_proto_goTypes = nil
	file_proto_trace_proto_depIdxs = nil
}
