/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameNnRouteImport } from './routes/game/nn'
import { Route as GameNewgameRouteImport } from './routes/game/newgame'
import { Route as GameMinimaxRouteImport } from './routes/game/minimax'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameNnRoute = GameNnRouteImport.update({
  id: '/game/nn',
  path: '/game/nn',
  getParentRoute: () => rootRouteImport,
} as any)
const GameNewgameRoute = GameNewgameRouteImport.update({
  id: '/game/newgame',
  path: '/game/newgame',
  getParentRoute: () => rootRouteImport,
} as any)
const GameMinimaxRoute = GameMinimaxRouteImport.update({
  id: '/game/minimax',
  path: '/game/minimax',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/minimax': typeof GameMinimaxRoute
  '/game/newgame': typeof GameNewgameRoute
  '/game/nn': typeof GameNnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/minimax': typeof GameMinimaxRoute
  '/game/newgame': typeof GameNewgameRoute
  '/game/nn': typeof GameNnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/minimax': typeof GameMinimaxRoute
  '/game/newgame': typeof GameNewgameRoute
  '/game/nn': typeof GameNnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/minimax' | '/game/newgame' | '/game/nn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/minimax' | '/game/newgame' | '/game/nn'
  id: '__root__' | '/' | '/game/minimax' | '/game/newgame' | '/game/nn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameMinimaxRoute: typeof GameMinimaxRoute
  GameNewgameRoute: typeof GameNewgameRoute
  GameNnRoute: typeof GameNnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/nn': {
      id: '/game/nn'
      path: '/game/nn'
      fullPath: '/game/nn'
      preLoaderRoute: typeof GameNnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/newgame': {
      id: '/game/newgame'
      path: '/game/newgame'
      fullPath: '/game/newgame'
      preLoaderRoute: typeof GameNewgameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/minimax': {
      id: '/game/minimax'
      path: '/game/minimax'
      fullPath: '/game/minimax'
      preLoaderRoute: typeof GameMinimaxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameMinimaxRoute: GameMinimaxRoute,
  GameNewgameRoute: GameNewgameRoute,
  GameNnRoute: GameNnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
